# Generated by Django 4.1.2 on 2022-10-27 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Med',
            new_name='Person',
        ),
    ]
